# CodingCoffee  qemu bmc , more courses : http://www.codingcoffee.org
tasks:
  - init: echo 'this is codingcoffee gitpod qemu from qemu.org ' # runs during prebuild
    command: mkdir build && cd build && ../configure && make
# CodingCoffee  qemu bmc,  more courses : http://www.codingcoffee.org
ports:
  - port: 3000
    onOpen: open-preview
