# CodingCoffee  qemu bmc , more courses : http://www.codingcoffee.org
tasks:
  - init: >
    mkdir build &&
    cd build    && 
    ../configure 
# CodingCoffee  qemu bmc,  more courses : http://www.codingcoffee.org
ports:
  - port: 3000
    onOpen: open-preview
